---
# 核心任务
- name: main
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common, tags: "role_common"}
    - { role: role_cloud, tags: "role_cloud"}
    - { role: role_nginx, tags: "role_nginx"}
    - { role: couchbase, tags: "couchbase"}
    - { role: preend, tags: "preend"}
    - { role: end, tags: "end"}
