- src: http://github.com/websoft9/role_common

- src: http://github.com/websoft9/role_cloud

- src: http://github.com/websoft9/role_nginx

- src: http://github.com/websoft9/role_couchbase

- src: http://github.com/websoft9/role_preend

- src: http://github.com/websoft9/role_end
